Add KINSOL JFNK interface
mfem/mfem pull request #1785
Opened 2020-09-25 21:32 UTC by jandrej

This PR adds the possibility to use KINSOL with a Jacobian Free Newton Krylov method to the Sundials interface

2020-09-27 20:09 UTC, tzanio commented
Cool stuff!

2020-09-29 22:21 UTC, kmittal2 commented on linalg/sundials.cpp
> +      }
We should be able to avoid duplicating the code here and L1801-1811.

2020-10-02 20:26 UTC, jamiebramwell approved these changes
This looks great!

2020-10-02 22:15 UTC, kmittal2 commented on linalg/sundials.cpp
> +   MFEM_ASSERT(flag == KIN_SUCCESS, "error in KINSetLinearSolver()");
Use `MFEM_VERIFY` instead?

2020-10-02 22:19 UTC, kmittal2 commented on linalg/sundials.cpp
> +            flag = SUNLinSolSetInfoFile_SPFGMR(LSA, stdout);
Seems like this will lead to an error without much explanation if SUNDIALS is not built with `-DSUNDIALS_BUILD_WITH_MONITORING=ON` option.

2020-10-02 22:20 UTC, kmittal2 requested changes
Besides a few minor comments, the PR looks good.

2020-10-06 17:18 UTC, kmittal2 approved these changes

2020-10-06 23:11 UTC, tzanio commented
@gardner48, I assume you are OK with this :)

2020-10-06 23:12 UTC, tzanio commented
Merged in `next` for testing...

2020-10-06 23:21 UTC, gardner48 approved these changes
This looks great to me, nice work Julian!

2020-10-12 21:31 UTC, tzanio commented
Please document in `CHANGELOG`

2020-10-12 21:38 UTC, tzanio commented on examples/sundials/ex10p.cpp
> +      kinsolver->SetJFNK(true);
Awesome 🤩

2020-10-12 22:26 UTC, tzanio approved these changes
Yet another awesome feature, thanks @jandrej! 🚀 

@gardner48, @kmittal2 and @jamiebramwell -- thank you for your help and reviews!

2020-10-12 22:26 UTC, merged