[WIP] hr-adaptivity based on TMOP
mfem/mfem pull request #1922
Opened 2020-12-07 23:01 UTC by kmittal2

This PR enables hr-adaptivity using TMOP-based error estimators.

2020-12-23 18:33 UTC, tzanio commented
Can you merge `master` here and resolve the conflicts please?

2020-12-28 20:26 UTC, vladotomov requested changes

2020-12-28 20:26 UTC, vladotomov commented on mesh/ncmesh.hpp
> +   int GetNGhostElements() const { return 0; }
Is this needed in the serial class? Seems that you only use the parallel class version.

2020-12-28 20:26 UTC, vladotomov commented on mesh/ncmesh.hpp
> +                                            Array<int> &new_ranks) {}
This seems to be relevant only in parallel. It could be defined only in the parallel class.

2020-12-28 20:26 UTC, vladotomov commented on mesh/ncmesh.hpp
> +                           Table &coarse_to_fine, int NGhost=0) const;
Could you add a comment about the difference with the existing version?

2020-12-28 20:26 UTC, vladotomov commented on mesh/pncmesh.hpp
> +                                            Array<int> &new_ranks);
This function can be `const`.

2020-12-28 20:26 UTC, vladotomov commented on mesh/pncmesh.cpp
> +   int target_elements = 0;
Is this `target_elements` some leftover debug computation?

2020-12-28 20:26 UTC, vladotomov commented on miniapps/meshing/mesh-optimizer.hpp
> +      new_ranks.SetSize(pmesh->GetNE());
Doesn't `new_ranks` come out of the `GetFineToCoarsePartitioning` call (above) with the correct size?

2020-12-28 20:26 UTC, vladotomov commented on miniapps/meshing/mesh-optimizer.hpp
> +class TMOPAMR
All these classes should be moved to `tmop_amr.hpp/cpp` in `/fem` s.t. they are available with the library.

2021-01-04 17:38 UTC, tzanio commented
Extending the review deadline to the end of the week...

2021-05-27 22:35 UTC, jandrej reviewed
I finished a first pass through the code and overall I can't find major roadblocks. I'll need some time to carefully go through all the new functionality though.

2021-07-01 00:40 UTC, vladotomov requested changes

2021-07-01 00:40 UTC, vladotomov commented on miniapps/meshing/mesh-optimizer.cpp
> +                  "1-3");
Expain the options (don't go into details, just something general that corresponds to the paper tests).

2021-07-01 00:40 UTC, vladotomov commented on miniapps/meshing/mesh-optimizer.cpp
> +                  "same options as metric_id");
Comment on the usage of `hmid`

2021-07-01 00:40 UTC, vladotomov commented on miniapps/meshing/mesh-optimizer.hpp
> +   int amr_type;
The name `amr` is confusing -- this has nothing to do with AMR, does it?

2021-07-22 14:52 UTC, vladotomov commented on fem/tmop.hpp
> +   void Update();
Should we name this `UpdateAfterMeshTopologyChange` to correspond to the other update function, and the function in `DiscreteTC`?

2021-07-22 14:52 UTC, vladotomov commented on fem/tmop_amr.hpp
> +class TMOPRefiner : public ThresholdRefiner
Do we need a whole new class? Can't we just create a `ThresholdRefiner` and call `SetTotalErrorFraction(0.)` right away?

2021-07-22 14:52 UTC, vladotomov commented on fem/tmop_amr.hpp
> +   void RebalanceParNCMesh();
Does it need to be public?

2021-07-22 14:52 UTC, vladotomov commented on fem/tmop_amr.cpp
> +                  break;
The `break` is inside the `if`, looks like an error.

2021-07-22 14:52 UTC, vladotomov commented on fem/tmop_amr.cpp
> +      double tmopenergy = pnlf->GetParGridFunctionEnergy(*x);
Seems that this calculation is not needed - it gets recomputed below every time.

2021-07-23 16:24 UTC, vladotomov commented on fem/tmop.hpp
> +   void SetMinSizeForTargets(double min_size_) { lim_min_size = min_size_; }
Explain the use of this.

2021-07-23 22:31 UTC, vladotomov approved these changes
Impressive work @kmittal2. This is a substantial amount of work that requires good understanding of the internal AMR specifics. Thank you!

2021-08-01 21:33 UTC, tzanio approved these changes

2021-08-01 21:33 UTC, tzanio commented
Merged in `next` for testing...

2021-08-01 21:34 UTC, tzanio commented
@rw-anderson and @jandrej -- please chime in if you have additional comments.

2021-08-08 23:31 UTC, merged

2021-08-09 16:39 UTC, v-dobrev commented
This sample run:
```console
mesh-optimizer -m stretched2D.mesh -o 2 -mid 2 -tid 1 -ni 50 -qo 5 -nor -vl 1 -alc 0.5 -no-vis
```
gives a different result in this PR:
```diff
-  Final strain energy: 0.00919635 = metrics: 0.00858393 + limiting term: 0.000612423
+  Final strain energy: 0.00919635 = metrics: 0.00919635 + limiting term: 0
```

2021-08-09 16:40 UTC, v-dobrev commented
Also
```console
mesh-optimizer -m stretched2D.mesh -o 2 -mid 2 -tid 1 -ni 400 -qo 5 -nor -vl 1 -alc 0.5 -st 1 -no-vis
```
gives
```diff
-  Final strain energy: 0.009217 = metrics: 0.00858223 + limiting term: 0.000634768
+  Final strain energy: 0.009217 = metrics: 0.009217 + limiting term: 0
```