Bugfix proposal for issue #1928
mfem/mfem pull request #1929
Opened 2020-12-08 14:44 UTC by latug0

Dear MFEM maintainer,
  This contribution intends to fix the reading of bi and tri-periodic meshes using GMSH format.
  Using the test case provided in issue #1928 , it provides satisfactory results.
  
   Guillaume.

2020-12-23 18:20 UTC, mlstowell commented on mesh/mesh_readers.cpp
> +         // Follow existing long chains of slave->master in v2v array. Finally,
Rather than "Finally, ..." it may be more clear to say "Upon completion of this loop each v2v[slave] will point to a true master vertex."

2020-12-23 18:22 UTC, mlstowell commented on mesh/mesh_readers.cpp
> +               // This loop is ending even if it happens
Perhaps we can say "This loop will end if it finds a circular dependency."

2020-12-23 18:24 UTC, mlstowell commented on mesh/mesh_readers.cpp
> +                  // the long chain has ended up to the vertex master
Perhaps we can say "the long chain has ended on the true master vertex"

2020-12-23 18:26 UTC, mlstowell requested changes
Just a few small changes to the comments are needed.

This is a good addition to the algorithm.  Thank you @latug0!

2020-12-24 10:04 UTC, latug0 commented
Thanks for your review @mlstowell.

2021-01-04 18:18 UTC, mlstowell approved these changes

2021-01-04 21:44 UTC, bslazarov commented
It seems that one of the checks does not pass. When I run examples with cube_2mat_per.msh or cube_2mat_per.mesh, I am receiving the following  msg:
Verification failed: (faces_info[i].Elem2No < 0 || faces_info[i].Elem2Inf%2 != 0) is false:
 --> invalid mesh topology
 ... in function: virtual void mfem::Mesh::Finalize(bool, bool)
 ... in file: /home/blaz/tmp/mfem/mesh/mesh.cpp:2636

The 2D case runs fine.

2021-01-05 07:52 UTC, latug0 commented
> It seems that one of the checks does not pass. When I run examples with cube_2mat_per.msh or cube_2mat_per.mesh, I am receiving the following msg:
> Verification failed: (faces_info[i].Elem2No < 0 || faces_info[i].Elem2Inf%2 != 0) is false:
> --> invalid mesh topology
> ... in function: virtual void mfem::Mesh::Finalize(bool, bool)
> ... in file: /home/blaz/tmp/mfem/mesh/mesh.cpp:2636
> 

Indeed, I get the same message and failure. If you change the `cl=.5;` into `cl=.2;` in the  cube_2mat_per.mesh.geo it will fix this issue. You will need to regenerate the mesh with `gmsh -3 cube_2mat_per.mesh.geo`. The zip file `periodicity_gmsh_v2.zip` of the issue #1928 has been changed accordingly.

I suspect the rationale for this strange behavior is the low number of nodes/edges in the configuration with `cl=.5`. The handling of periodic meshes in this case seems difficult.

2021-01-05 18:38 UTC, mlstowell commented
The mesh produced by Gmsh when `cl=.5` has only two edges connecting some master/slave pairs of vertices.  MFEM cannot support such meshes because it uses vertices to identify edges in the mesh.  Imagine the first such edge ends at vertices `v0` and `v1` and the second edge goes from `v1` to `v2`.  Now identify vertices `v0` and `v2` as a master/slave pair.  We're left with two edges from `v1` to `v0` and MFEM can no longer distinguish them.

For this reason we require a minimum of three elements across periodic meshes.  Unfortunately this is not something that can be easily verified before eliminating slave vertices.

2021-01-05 18:55 UTC, bslazarov approved these changes
Great contribution! Thanks!

2021-01-06 08:07 UTC, latug0 commented
Thanks for the given explanation, very clear.
Maybe I would suggest to improve the following error message:
`Verification failed: (faces_info[i].Elem2No < 0 || faces_info[i].Elem2Inf%2 != 0) is false`. It does not provide/suggest any clue about what went wrong to the end user.  Perhaps, one should add some words about detection of wrong orientation of some faces during the mesh reading ?

2021-01-06 19:48 UTC, mlstowell commented
Hi, @latug0 and @bslazarov ,

You are absolutely correct.  We should have a more meaningful error message here.  I just created a PR (#1981) which adds checks that catch this error a little earlier in the mesh construction process.  We still can't determine exactly why this mesh is bad but catching it earlier does allow us to provide a bit more information in the error message.

Once this PR passes the CI tests I'll add you as a reviewer if you'd like to offer any feedback.

Best wishes,
Mark

2021-01-19 20:25 UTC, v-dobrev commented
Merged in `next` for testing...

2021-02-04 22:34 UTC, merged