llow user to specify initial guess in AmgXSolver
mfem/mfem pull request #2132
Opened 2021-03-25 02:21 UTC by wcdawn

2021-03-25 03:12 UTC, artv3 approved these changes
Looks good to me, but I wonder if false should be the default?

2021-03-25 12:09 UTC, wcdawn commented
I set it this way to not change the default behavior of the code but I agree that setting `zero_guess=false` by default would probably be better. `zero_guess=false` would reflect the default behavior of, for example, `CGSolver`.

2021-03-25 14:33 UTC, tzanio commented
It really depends if we expect that its typical use is as a solver or as a preconditioner. In the former case, `zero_guess` should be `false`. In the latter case, it should be `true`.

2021-03-25 14:35 UTC, tzanio commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2021-03-25 15:18 UTC, barker29 requested changes
Other than my minor suggestion, this PR is a nice improvement.

2021-03-25 15:18 UTC, barker29 commented on linalg/amgxsolver.hpp
> +   bool zero_guess = true;
Following @tzanio 's comment, can you set the `zero_guess` value based on `amgxMode` in `DefaultParameters()` method so it's `false` for a solver and `true` for a preconditioner?

2021-03-25 15:28 UTC, wcdawn commented
I've changed how this is implemented to avoid having to choose a default and be more consistent with the rest of MFEM. Now, the behavior is based on the `iterative_mode` boolean from the parent `Solver` class. 

I've also implemented @barker29 request to set the iterative mode based on whether the class is being used as a solver or preconditioner. As such, I've removed the setter function because it should be unnecessary now.

Thanks for the help!

2021-03-25 15:47 UTC, barker29 approved these changes
Looks good!

2021-03-25 15:52 UTC, tzanio commented
@artv3 can you confirm you are OK with the latest changes?

2021-03-25 17:21 UTC, artv3 commented
Yup looks good to me!

2021-03-25 17:55 UTC, tzanio commented
Merged in `next` for testing...

2021-03-27 19:11 UTC, tzanio approved these changes
Thanks @wcdawn !

2021-03-27 19:11 UTC, merged