Scale LOR integrated basis if using map type VALUE [lor-scale-integrated]
mfem/mfem pull request #2753
Opened 2022-01-05 17:46 UTC by pazner

The LOR basis `IntegratedGLL` gives a spectrally equivalent L2 mass matrix when using map type `INTEGRAL`, but when using map type `VALUE`, it requires an additional scaling by the LOR subcell size.

This PR implements that scaling whenever map type is `VALUE`. See also #2752.

2022-01-06 19:46 UTC, mlstowell commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2022-01-06 19:50 UTC, mlstowell commented
@pazner, can you recommend a way to test these changes? I noticed your PR #2752 has a new unit test although I have not looked at either PR closely yet. Is it possible that unit test would also test these changes? If not, is there some simple unit test we could add to this PR?

2022-01-06 19:59 UTC, pazner commented
Yes, #2752 has unit test that should fail on master, and pass on that branch.

The situation with this PR is a bit more complicated — the code will "work" as it is in master, but the conditioning will not be good. The "easiest" way of testing this would be to apply this patch:

<details>
<summary>Click to expand</summary>

```diff
diff --git a/miniapps/solvers/lor_solvers.cpp b/miniapps/solvers/lor_solvers.cpp
index dac300971..ee4ab022b 100644
--- a/miniapps/solvers/lor_solvers.cpp
+++ b/miniapps/solvers/lor_solvers.cpp
@@ -113,7 +113,7 @@ int main(int argc, char *argv[])
    if (H1) { fec.reset(new H1_FECollection(order, dim, b1)); }
    else if (ND) { fec.reset(new ND_FECollection(order, dim, b1, b2)); }
    else if (RT) { fec.reset(new RT_FECollection(order-1, dim, b1, b2)); }
-   else { fec.reset(new L2_FECollection(order, dim, b1)); }
+   else { fec.reset(new L2_FECollection(order, dim, b2)); }
 
    FiniteElementSpace fes(&mesh, fec.get());
    cout << "Number of DOFs: " << fes.GetTrueVSize() << endl;
@@ -126,7 +126,6 @@ int main(int argc, char *argv[])
    if (H1 || L2)
    {
       a.AddDomainIntegrator(new MassIntegrator);
-      a.AddDomainIntegrator(new DiffusionIntegrator);
    }
    else
    {
@@ -137,8 +136,6 @@ int main(int argc, char *argv[])
    else if (RT) { a.AddDomainIntegrator(new DivDivIntegrator); }
    else if (L2)
    {
-      a.AddInteriorFaceIntegrator(new DGDiffusionIntegrator(-1.0, kappa));
-      a.AddBdrFaceIntegrator(new DGDiffusionIntegrator(-1.0, kappa));
    }
    // TODO: L2 diffusion not implemented with partial assembly
    if (!L2) { a.SetAssemblyLevel(AssemblyLevel::PARTIAL); }
```
</details>

and then run
```
./lor_solvers -fe l -o 10
```
and compare iterations between master and this branch (89 vs. 23).

2022-01-06 20:01 UTC, mlstowell commented
>

2022-01-11 05:38 UTC, dylan-copeland requested changes
The changes look reasonable, and I verified that convergence is improved for the `lor_solvers` test described above. The only issue is a lack of documentation, although documentation would be uncharacteristic for the `Poly_1D` class. This is not a fault of this PR, and requesting thorough documentation for the entire class would be scope creep. However, I think more documentation is necessary to understand the changes in this PR. Would it be hard to add enough documentation to make the changes in this PR clearly understandable, or should that be done in a future PR? By "documentation" I mean sufficient details to understand the polynomials being computed in all the supported cases, perhaps with references to literature defining the polynomials.

2022-01-11 17:24 UTC, pazner commented
I added some Doxygen documentation, let me know how it looks to you.

2022-01-11 18:16 UTC, dylan-copeland commented on fem/fe/fe_base.hpp
> +      /// @brief An auxuliary nodal basis used to evaluate the integrated basis.
auxuliary

2022-01-11 18:16 UTC, dylan-copeland commented on fem/fe/fe_base.hpp
> +      /// This basis  is given by the negative partial sum of the corresponding
extra space

2022-01-11 18:27 UTC, dylan-copeland approved these changes
Thanks for adding documentation!

2022-02-01 18:47 UTC, mlstowell approved these changes

2022-02-08 20:45 UTC, tzanio approved these changes
Very nice, @pazner !

2022-02-15 21:57 UTC, merged