[WIP] Update surface fitting formulation
mfem/mfem pull request #2825
Opened 2022-02-11 20:04 UTC by kmittal2

- Update formulation to be pointwise
- Set surface fitting term's weight adaptively
- Enable surface fitting error based termination of TMOP solver

2022-02-15 17:09 UTC, tzanio commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2022-03-04 20:07 UTC, vladotomov requested changes

2022-03-04 20:07 UTC, vladotomov commented on fem/tmop_tools.cpp
> +   {
You should add 2 sentences about the general idea of the adaptive weight, or add more comments to the important lines below.

2022-03-04 20:07 UTC, vladotomov commented on fem/tmop.cpp
>     const FiniteElement &el_s = *surf_fit_gf->FESpace()->GetFE(el_id);
Function params `ir_quad` and `weights` can be removed, and the same for the `GradSurfFit` function.

2022-03-04 20:07 UTC, vladotomov commented on fem/tmop.cpp
> +   if (count == 0) { return; }
The `count` check can be moved earlier, and the same for the `GradSurfFit` function.

2022-03-04 20:07 UTC, vladotomov commented on fem/tmop.cpp
> +void TMOP_Metric_000::EvalP(const DenseMatrix &Jpt, DenseMatrix &P) const
I think simply `P=0` should work fine.

2022-03-04 20:07 UTC, vladotomov commented on fem/tmop.cpp
> +                                DenseMatrix &A) const
`A=0`

2022-03-04 20:07 UTC, vladotomov commented on miniapps/meshing/pmesh-optimizer.cpp
> +      case 0: metric = new TMOP_Metric_000; break;
Can users actually use this one?

2022-03-04 20:07 UTC, vladotomov commented on miniapps/meshing/pmesh-optimizer.cpp
>  //  Adaptive surface fitting:
Add corresponding changes in `mesh-optimizer`.

2022-03-10 01:15 UTC, vladotomov approved these changes
Works great, good job @kmittal2.

2022-03-13 00:27 UTC, tzanio approved these changes

2022-03-13 00:28 UTC, tzanio commented
Merged in `next` for testing...

2022-03-14 15:46 UTC, tzanio commented
Re-merged in `next` for testing...

2022-03-15 15:11 UTC, merged