Optimize PADGTraceSetup{2D,3D}
mfem/mfem pull request #2935
Opened 2022-03-25 00:09 UTC by artv3

The comments had a great idea! Let's expose more parallelism.

2022-03-25 16:20 UTC, YohannDudouit requested changes
I think it's a bit more clear to use `MFEM_FOREACH_THREAD` with `MFEM_FORALL_3D`.

2022-03-25 16:20 UTC, YohannDudouit commented on fem/bilininteg_dgtrace_pa.cpp
> +   MFEM_FORALL(tid, Q1D*NF,
This may be a bit more clear:
```suggestion
   MFEM_FORALL_3D(f, NF, Q1D, 1, 1,
```

2022-03-25 16:20 UTC, YohannDudouit commented on fem/bilininteg_dgtrace_pa.cpp
> +      const int q = tid % Q1D;
```suggestion
      MFEM_FOREACH_THREAD(q, x, Q1D)
```

2022-03-25 16:20 UTC, YohannDudouit commented on fem/bilininteg_dgtrace_pa.cpp
> +   MFEM_FORALL(tid, Q1D*Q1D*NF,
```suggestion
   MFEM_FORALL_3D(f, NF, Q1D, Q1D, 1,
```

2022-03-25 16:20 UTC, YohannDudouit commented on fem/bilininteg_dgtrace_pa.cpp
> +      int q1 = tid % Q1D;
```suggestion
MFEM_FOREACH_THREAD(q1, x, Q1D)
```

2022-03-25 16:20 UTC, YohannDudouit commented on fem/bilininteg_dgtrace_pa.cpp
>           {
```suggestion
         MFEM_FOREACH_THREAD(q2, y, Q1D)
         {
```

2022-03-25 19:40 UTC, pazner commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2022-03-28 19:29 UTC, YohannDudouit commented
> I'm okay with the proposed changes, however; just to double check isn't preferable to have a higher thread per block count than what is proposed? For the 3D case if Q1D is 4 then we have 16 vs the 256 as previously proposed.

You're right, this is probably more efficient.

2022-03-30 16:07 UTC, YohannDudouit approved these changes

2022-04-04 15:33 UTC, camierjs approved these changes

2022-04-11 16:08 UTC, merged