Sundials IDA solver integration [ida-dev]
mfem/mfem pull request #3690
Opened 2023-05-24 01:29 UTC by sbugenha

This branch adds a wrapper for the Sundials IDA solver. It also adds an abstract base class for solving systems of differential algebraic equations (DAEs).

2023-07-20 19:07 UTC, v-dobrev commented
@sbugenha, is this PR ready for review?

2023-07-20 20:00 UTC, sbugenha commented
> @sbugenha, is this PR ready for review?

Hey @v-dobrev - yeah, this is ready for review. I saw there is a code style issue but it runs fine. Thanks for checking in!

2023-08-12 16:36 UTC, tzanio commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2023-08-15 02:09 UTC, sbugenha commented
Hi @cjvogl, 

> 1. Can you elaborate on the introduction of the abstract class DAESolver? It appears it defines some implementation and is only derived by IDASolver, so why not put the implementation (data structures, non-pure virtual methods, etc.) that are currently in DAESolver into IDASolver?

The purpose of the DAESolver abstract class is analogous to the existing ODESolver abstract class, but for DAEs. The only difference between ODESolver and DAESolver is in the Step and Run functions, which for the DAESolver requires both x and x' as input vectors, whereas ODESolver allows only x as an input vector. It's only a small change, and IDASolver is already pretty well self-contained and could function without it.

> 2. Are you able to address the style check failure?

I can try when I get some time. I'm not that familiar with the style requirements so it might be a little while before I get a chance to look into this. 

> 3. Can you add some "driver" code that calls this code? Perhaps in one of the SUNDIALS examples or as a unit test?

I just added a version I had of Example 16 that uses IDA. Let me know if this is helpful. If I get some time I can try to modify the Sundials examples as well to include IDA.

2023-08-16 22:35 UTC, sbugenha commented
I'll leave up to you whether to just have IDASolver derive from ODESolver and override the Step and Run functions or to include a separate DAESolver class. I personally do think it's helpful having a separate interface for implicit solvers, and I think there are other classes that could benefit from this as well. For example, I'm currently writing a NonlinearForm integrator and had to write a derived version of the NonlinearForm and NonlinearFormIntegrator classes to introduce implicit versions of the Mult and AssembleElementVector functions in those classes that take both x and x' as input arguments.

2023-08-16 22:57 UTC, cjvogl commented
> I'll leave up to you whether to just have IDASolver derive from ODESolver and override the Step and Run functions or to include a separate DAESolver class

My preference is to not introduce an abstract class with only one derived class.  I am more open to introducing an interface (i.e., a class without no implementation details so that the derived classes are free to choose the implementation), but I'm not sure that would be useful here as I don't see anywhere `IDASolver` is passed around as a `DAESolver`.

> For example, I'm currently writing a NonlinearForm integrator and had to write derived versions of the NonlinearForm and NonlinearFormIntegrator classes to introduce implicit versions of the Mult and AssembleElementVector functions in those classes that take both x and x' as input arguments.

My suggestion is to stick with `IDASolver` deriving directly from `ODESolver` in this PR and introduce an interface in a future PR when there is more derived classes... perhaps with the work you are describing here.

2023-08-16 23:14 UTC, cjvogl commented
> I just added a version I had of Example 16 that uses IDA. Let me know if this is helpful. If I get some time I can try to modify the Sundials examples as well to include IDA.

Thank you for including that example code: it will be good to have some code to test your new features.

I will note that adding a new example to the code base will require additional work to ensure it is maintainable as new features are added to MFEM (e.g., support of new SUNDIALS features or API changes), including documentation on the MFEM webpage for any new examples (see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#developer-guidelines).

@tzanio , perhaps someone from the SUNDIALS team will want to weigh in here?

2023-08-18 02:45 UTC, sbugenha commented
> My suggestion is to stick with IDASolver deriving directly from ODESolver in this PR and introduce an interface in a future PR when there are more derived classes... perhaps with the work you are describing here.

Makes sense, I think this sounds reasonable. 

Thanks for the guidelines regarding the example codes. It may be possible to simply update the existing SUNDIALS examples with just a few changes to allow them to run IDA as a solver option. The biggest change from the ode solvers in those codes would be the need for the code to provide a consistent initial condition for both x and x' in IDA. Although in those examples, a DAE formulation isn't really necessary to solve the problem. Might be worth making a new example or miniapp that illustrates a problem where a DAE formulation is most convenient for the physics. The incompressible Navier Stokes equations come to mind where a DAE formulation would allow for a fully coupled solution without the need for operator splitting. This is something I'm currently building.

2023-08-22 18:44 UTC, tzanio commented
@gardner48, can you take a look at this when you get a chance?

2023-10-24 16:30 UTC, tzanio commented
Code styling is failing, can you please run `make style`

2023-10-24 16:30 UTC, tzanio commented
Code styling is failing, can you please run `make style`

2023-11-12 18:39 UTC, tzanio commented
ping: @gardner48

2025-07-29 16:00 UTC, cjvogl requested changes
My understanding is that there's an open question as to whether or not `ex16ida.cpp` should be merged with the existing SUNDIALS ex16 or not.

2026-06-10 03:37 UTC, closed without merging