[WIP] Surface fitting updates
mfem/mfem pull request #4116
Opened 2024-02-07 00:33 UTC by kmittal2

Misc updates related to surface fitting capability.

2024-02-13 22:40 UTC, tzanio commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2024-03-22 01:06 UTC, vladotomov requested changes

2024-03-22 01:06 UTC, vladotomov commented on fem/tmop.cpp
> +   // Unify marker array across processor boundaries
Why would they be different?
Shouldn't this be done by the caller?

2024-03-22 01:06 UTC, vladotomov commented on fem/tmop.cpp
> +    fec_grad,
Is this some editor malfunction?

2024-03-22 01:06 UTC, vladotomov commented on fem/tmop.cpp
> +               surf_fit_gf_energy += surf_fit_coeff->Eval(*Tpr, ip_s) *
I thought user-provided `Coefficients` were not part of the normalization. They would get cancelled out and have no effect.

2024-03-22 01:06 UTC, vladotomov commented on fem/tmop_tools.hpp
> +       the weight and the termination of the solver. (Experimental) */
Don't you need `///@{  ... ///@}` to actually group the functions in the doxygen.

2024-03-22 02:51 UTC, kmittal2 commented on fem/tmop.hpp
> +class TMOP_Metric_000 : public TMOP_QualityMetric
Not in this PR but Mathias is using it in LiDO.

2024-03-22 03:08 UTC, kmittal2 commented on fem/tmop.hpp
> +   void ReMapSurfaceFittingLevelSet(GridFunction &s0);
Added an example of this being used in the miniapp.

2024-03-25 23:06 UTC, kmittal2 commented
After discussion with @vladotomov, I will be breaking this into smaller PRs.

2024-03-25 23:06 UTC, closed without merging