CMake improvements
mfem/mfem pull request #4561
Opened 2024-10-31 01:47 UTC by helloworld922

Allow other projects to link to MFEM without directly needing to know about CUDA/HIP.

This allows an application to link to an MFEM install without knowing too much about how MFEM was built.

Example application CMakeLists.txt linking to GPU accelerated MFEM:

```{CMake}
cmake_minimum_required(VERSION 3.19)
project(my_project CXX)

find_package(MFEM REQUIRED)

# my_app.cpp doesn't have any CUDA or HIP code directly, but can use MFEM's GPU accelerated code
add_executable(my_app my_app.cpp)
target_link_libraries(my_app PUBLIC mfem)
```

2024-12-03 19:58 UTC, tzanio commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2025-03-12 17:55 UTC, helloworld922 commented
Added a change which fixes #4732

2025-03-12 18:40 UTC, cjvogl commented
Just my opinion, but the scope of this PR appears to be growing from 1) some targeted changes in CMake to support
```
cmake_minimum_required(VERSION 3.8)
project(my_project CXX)

find_package(MFEM REQUIRED)

# my_app.cpp doesn't have any CUDA or HIP code directly, but can use MFEM's GPU accelerated code
add_executable(my_app my_app.cpp)
target_link_libraries(my_app PUBLIC mfem) 
```
to 2) including some improvements/fixes in 900085cb to the `MFEM_REGISTER_KERNEL` macro outside of the CMake system to 3) also including a bug fix in ffe14214 address `HYPRE_VERSION` corruption noted in issue #4732.

This type of scope creep is making the PR difficult for me to review, particular because I do not have familiarity with both CMake **and** the MFEM kernel dispatch.  TLDR: I find more, smaller PRs easy to review.

2025-03-12 20:20 UTC, helloworld922 commented
I split off the fix for #4732 and the macro namespace related changes into separate PR's.

2025-03-13 20:29 UTC, cjvogl commented on CMakeLists.txt
> +   if ("all" STREQUAL CUDA_ARCH)
Is putting the value first and variable second a standard convention? It looks like `cmake/modules/MfemCmakeUtilities.cmake` has adopted a convention that is the reverse, e.g.,
``` cmake
if (cache_type STREQUAL "UNINITIALIZED")

2025-03-13 20:44 UTC, cjvogl commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
Can this be implemented by adding `CUDA::cudart` to `MFEM_TPLS` (see [an example for MPI::MPI_CXX](https://github.com/mfem/mfem/blob/cmake-replace-library-files-with-targets/CMakeLists.txt#L571))?  The context for the question is that I am concerned other users will add to this conditional statement with other `elseif` statements in the future.

2025-03-13 20:45 UTC, cjvogl requested changes
Everything compiled for me.  My only concerns are on the implementation (and posted as in-line comments)

2025-03-14 00:05 UTC, helloworld922 commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
Yes, that appears to work. Do you want to leave that as a separate PR, or should we try to combine the two branches into a single PR since I believe with the other branch you would also need to add additional modifications to `MFEMConfig.cmake.in` to find dependencies for `TPL_TARGETS`?

2025-03-14 00:08 UTC, helloworld922 commented on CMakeLists.txt
> +   if ("all" STREQUAL CUDA_ARCH)
fixed

2025-03-14 17:17 UTC, jandrej commented on config/cmake/MFEMConfig.cmake.in
> +    # alternatively could check HYPRE_USING_HIP
I would like to see a check for `HYPRE_USING_HIP` and cmake giving a configure error if that's not the case.

2025-03-14 17:40 UTC, helloworld922 commented on config/cmake/MFEMConfig.cmake.in
> +    # alternatively could check HYPRE_USING_HIP
I don't think that's possible here without effectively reproducing the compile check in our `FindHYPRE.cmake` since that file is not installed (and shouldn't to prevent clashing with HYPRE built and installed with CMake).

Thankfully(?) the installed `MFEMTargets.cmake` uses absolute paths when linking against HYPRE, so as long as the HYPRE at that location hasn't changed then hopefully `HYPRE_USING_HIP` will also not have changed since MFEM was installed, which will be checked and error out if not true.

Ideally the best solution would be to just remove our `FindHYPRE.cmake` and rely on the HYPRE installed cmake files, however this would not work with HYPRE built and installed with autoconf/gnu make.

2025-03-14 17:54 UTC, helloworld922 commented on config/cmake/MFEMConfig.cmake.in
> +    # alternatively could check HYPRE_USING_HIP
I thought it was, but it looks like it isn't? Same with `HYPRE_USING_CUDA`. I can add those checks to MFEM.

2025-03-14 18:06 UTC, helloworld922 commented on config/cmake/MFEMConfig.cmake.in
> +    # alternatively could check HYPRE_USING_HIP
I think I'm going to leave this out for now. It looks like the HYPRE cmake files use different names for these (`HYPRE_WITH_X` vs. `HYPRE_USING_X`), and other packages which could use GPUs also do not perform this check right now.

2025-03-17 21:20 UTC, cjvogl commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
FWIW, I realize that you are aware of the discussion given you reviewed that PR (thank you for that, btw)... my statement here about the discussion is more for other readers of this thread who were not involved in #4673.

2025-03-31 16:30 UTC, cjvogl commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
I apologize for any confusion I caused, but I **do** think `CUDA::cudart` should be added to `MFEM_TPLS` on line 593 instead of having this separate conditional statement.

2025-03-31 19:54 UTC, helloworld922 commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
In order to add `CUDA::cudart` to `MFEM_TPLS` requires the other changes in the `cmake-replace-libraries` branch. Did you want me to push `CUDA::cudart` to that branch? The changes to `MFEMConfig.cmake.in` also don't really work without this. Perhaps these two branches should really be combined into a single PR since that branch deals with finding the dependencies inside of MFEM, while this one makes sure that when external users do `find_package(MFEM)` it will also find those dependencies.

2025-03-31 20:24 UTC, cjvogl commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
I don't think all the changes in `cmake-replace-libraries` are needed here.  Can you add `CUDA::cudart` to `MFEM_TPLS` and then add a check inside the for loop, i.e., something like
``` cmake
# Add all *_FOUND libraries in the variable TPL_LIBRARIES.
set(TPL_LIBRARIES "")
set(TPL_INCLUDE_DIRS "")
foreach(TPL IN LISTS MFEM_TPLS)
  if (${TPL}_FOUND)
    message(STATUS "MFEM: using package ${TPL}")
    if (TARGET ${TPL})
      list(APPEND TPL_LIBRARIES ${TPL})
    else()
      list(APPEND TPL_LIBRARIES ${${TPL}_LIBRARIES})
      list(APPEND TPL_INCLUDE_DIRS ${${TPL}_INCLUDE_DIRS})
    endif()
  endif()
endforeach(TPL)
```
?

2025-03-31 21:32 UTC, helloworld922 commented on CMakeLists.txt
> +endif (MFEM_USE_CUDA)
Ok, it should work now.

2025-04-01 02:11 UTC, cjvogl requested changes
Everything compiles but I don't have a machine to run CUDA code on at the moment. I did note an warning message during configuration:
``` bash
--  *** Warning: [CUDA::cudart] uses target type 'UNKNOWN_LIBRARY' which is not supported!
```
which I suppose might be because I'm compiling on machine that doesn't have GPUs?

If you can verify that you are not seeing this message during configuration, I'll go ahead with approval.  Otherwise, that message should be addressed before this PR is merged.

2025-04-01 03:55 UTC, helloworld922 commented
Hmm, the target being `UNKNOWN_LIBRARY` is a known issue with CMake (https://gitlab.kitware.com/cmake/cmake/-/issues/23516), however it shouldn't show up if `MFEM_USE_CUDA` isn't enable. I can dig into how to fix this.

2025-04-01 04:20 UTC, helloworld922 commented
Hmm, I think I figured out why. The logic for [finding targets](https://github.com/mfem/mfem/blob/7c80866b4930d3572035a96ea14dceb74d98694e/CMakeLists.txt#L604) only excludes a CMake-style target if the target doesn't exist, not if it was requested to be used.

For me this shows up because I have HYPRE built with CUDA, so our `FindHYPRE.cmake` will run `find_package(CUDAToolkit)`. This will then run into a problem in the generated `MFEMConfig.cmake` since even though `MFEM_USE_CUDA` is disabled, we are still linking to `CUDA::cudart`. In principle this could happen with other targets if somehow they get discovered, but MFEM isn't configured to use them.

I think the only way to fix this is to add something like `MFEM_DEPENDS_ON_CUDART` to `MFEMConfig.cmake.in` and use that to pull in the CUDAToolkit dependency (and likewise for other TPL dependencies), but I don't necessarily like that solution.

2025-04-02 00:40 UTC, cjvogl commented
> Hmm, the target being UNKNOWN_LIBRARY is a known issue with CMake

I've had more time to look into this: my concern is that there's a warning message being generated by mfem_get_target_options when there should not be... or at least, that's how I currently understand what you've said. Please correct me if I have the wrong understanding, but otherwise I imagine the message can be avoided by some additional checks in `mfem_get_target_options`... perhaps something like this patch:

``` bash
diff --git a/config/cmake/modules/MfemCmakeUtilities.cmake b/config/cmake/modules/MfemCmakeUtilities.cmake
index 02216bbd2b..47250fb217 100644
--- a/config/cmake/modules/MfemCmakeUtilities.cmake
+++ b/config/cmake/modules/MfemCmakeUtilities.cmake
@@ -776,9 +776,11 @@ function(mfem_get_target_options Target CompileOptsVar LinkOptsVar)
     # INTERFACE_LINK_DIRECTORIES
     # INTERFACE_LINK_OPTIONS
   else()
-    message(STATUS " *** Warning: [${tgt}] uses target type '${type}'"
-      " which is not supported!")
     set(AddInterfaceLinkLibs FALSE)
+    if (NOT "${type}" STREQUAL "UNKNOWN_LIBRARY")
+      message(STATUS " *** Warning: [${tgt}] uses target type '${type}'"
+        " which is not supported!")
+    endif()
   endif()
   if (AddInterfaceLinkLibs)
     get_target_property(Libs ${tgt} INTERFACE_LINK_LIBRARIES)
```

Then again, perhaps I'm not understanding why a target with `UNKNOWN` type is not supported by mfem's cmake.

2025-04-02 17:38 UTC, cjvogl commented
> It looks like on some platforms (Windows) UNKNOWN is used 

My understanding is that the UNKNOWN target type is used on all platforms after [this commit](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6286/diffs#ed3b1529aa16f8c35092ca8535bc47e248a7c967_848_847).  I do see it on LC machines.

> I looked in the generated config.mk file which uses mfem_get_target_options to create, and I don't see anything like -lcudart_static, -lcudart, or -lcudadevrt which linking against CUDA::cudart is supposed to add.

Ok, that does sound like it will be an issue with pure makefile build system (but I'm not familiar with that).  In any case, sounds like there's some issues that need be worked out before this PR should go in.  Feel free to disagree.

2025-04-02 17:55 UTC, helloworld922 commented
Yes, it is used on all platforms, and I agree we should come up with a proper fix before this is merged. I'll look into that.

2025-04-12 22:58 UTC, helloworld922 commented
@cjvogl I think the UNKNOWN_LIBRARY issue should be fixed now? I can see cudart at least being in the linker flags in the generated cmake file. The CMake targets change also broke linking to RAJA, which should be fixed now.

2025-04-14 16:10 UTC, cjvogl commented on config/cmake/modules/MfemCmakeUtilities.cmake
> +        "-l${LibName}")
My initial reaction is that changing the conditional statement would be better than copy-paste of the conditional body, i.e., changing
```
elseif ("${type}" STREQUAL "SHARED_LIBRARY")
```
to something like
```
elseif ("${type}" STREQUAL "SHARED_LIBRARY" OR "${type}" STREQUAL "UNKNOWN_LIBRARY")
```
Perhaps there's an advantage to the copy-paste approach that I'm missing?

2025-08-21 21:46 UTC, helloworld922 commented
@jandrej @camierjs @cjvogl @v-dobrev any chance you could take another look at this? I've been maintaining these changes as a git stash so I can apply these to other branches when I want to test/use them.

2025-08-21 23:50 UTC, cjvogl approved these changes

2025-08-21 23:51 UTC, cjvogl commented
> @jandrej @camierjs @cjvogl @v-dobrev any chance you could take another look at this? I've been maintaining these changes as a git stash so I can apply these to other branches when I want to test/use them.

Sorry this fell off my radar!  I either missed or never got a notification when the prior threads were resolved.

2025-09-21 17:29 UTC, camierjs commented on CMakeLists.txt
> +   # RAJA uses FindCUDA, which needs CMP0145=OLD in CMake >= 3.27
```suggestion
   # RAJA uses FindCUDA, which needs CMP0146=OLD in CMake >= 3.27
```

2025-09-22 14:37 UTC, tzanio commented
Merged in `next` for testing...

2025-09-25 17:30 UTC, merged