[WIP] Experimental solution to BC selection issue in ex1 and ex1p
mfem/mfem pull request #4630
Opened 2024-12-12 23:08 UTC by mlstowell

PR #4484 corrects an issue with reading periodic meshes which happen to contain internal boundaries. Our mesh reader would remove such boundaries because the periodic surfaces are often defined in terms of boundaries which become internal when the mesh is stitched together. MFEM's mesh reader makes the assumption that this particular internal boundary will not be needed. This may or may not be a correct assumption. However, MFEM goes a step further and removes _all_ internal boundaries. This is clearly overly aggressive so PR #4484 does the right thing by leaving internal boundaries in place.

PR #4484 exposes an issue with examples `ex1` and `ex1p` which make the assumption that an essential boundary condition should be applied to _all_ boundaries in the supplied meshes. However, the original intention of examples `ex1` and `ex1p` would seem to have been that an essential boundary condition should be applied to all exterior surfaces of the supplied meshes.

This PR seeks to provide functionality in the `(Par)FiniteElementSpace` classes to easily identify degrees of freedom lying on the exterior surfaces regardless of what surfaces the mesh designer chose to label with boundary attributes.

There is, of course, the possibility that this PR will still lead to differences in certain test runs of examples `ex1` and `ex1p`. For example if a mesh does not tag all of its exterior surfaces with boundary attributes this PR will produce a larger set of essential DoFs than the original code would have.

2024-12-14 19:46 UTC, tzanio commented
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

2024-12-15 21:31 UTC, v-dobrev commented
Since #4484 in already in `next`, it will be better for this PR to be merged there instead of directly into `master`.

2024-12-15 22:35 UTC, v-dobrev commented
I don't think we need to add the new methods,`(Par)FiniteElementSpace::GetExterior{VDofs,GetExteriorTrueDofs}`, to solve the issue at hand. These seem too specialized and in example 1/1p we should illustrate the general approach we want users to use for handling boundary conditions -- using the boundary-attribute marker arrays. This approach is used in all examples and using a different approach in example 1/1p is not appropriate in my view.

I can suggest a few approaches that do not go around the use of boundary-attribute marker arrays:
1. Add a virtual method, e.g. called `(Par)Mesh::RemoveInternalBoundaries(Array<int> &bdr_marker)`, that we can call after the lines `ess_bdr = 1;` to un-mark boundary attributes corresponding to interior boundaries; or
2. Add a virtual method, e.g. called `(Par)Mesh::MarkExternalBoundaries(Array<int> &bdr_marker)` that we call instead of `ess_bdr = 1;` to mark boundary attributes corresponding only to real "exterior" boundaries; or
3. Add another optional parameter to `(Par)FiniteElementSpace::GetEssentialTrueDofs` -- `bool remove_interior = false` that we can set to `true` in example 1/1p; this parameter will probably need to be propagated to other methods used by `GetEssentialTrueDofs`, e.g. `GetEssentialVDofs`.

2024-12-16 19:31 UTC, mlstowell commented
I think the methods proposed by @v-dobrev could each be useful but they all involve assumptions. We have no control over which surfaces mesh designers will choose to mark with boundary attributes. There is no guarantee that every exterior face will have a boundary attribute. There is no guarantee that every boundary attribute will contain only interior or exterior faces, some could be a mixture of the two.

On the other hand I do agree that these examples should showcase the preferred manner of setting boundary conditions. We could add a small amount of logic to handle both options. Perhaps offer a command line option to input the boundary attributes. If this option is not used then set all exterior DoFs as in this PR.

If the consensus is that this PR does not resolve the issue in the best way, I certainly don't mind withdrawing it.

2025-01-15 16:01 UTC, tzanio commented
Sorry for the delayed response. Here are my thoughts on this:

1. I think `GetExteriorTrueDofs` and the additional functions [suggested](https://github.com/mfem/mfem/pull/4630#issuecomment-2544139639) by Veselin are all useful and we should add them

2. However I would prefer Example 1 to be as easy to understand and modify to user needs as possible.

3. From the perspective of 2, I think the best ways to specify essential BC, in order user-friendliness are

     a. A named attribute in the mesh files with expected name, e.g. "Dirichlet" or "Essential"

     b. Boundary attribute numbers

     c. The whole external boundary

4. I suggest that in Example 1, first we check for 3a, and if not present, then use the current attribute approach followed by `RemoveInternalBoundaries` and finally add a comment that the whole boundary can be easily marked with `GetExteriorTrueDofs`

5. In this PR we also modify the Gmsh meshes to have the named attribute from 3a

6. Most problems will have essential conditions on part of the boundary, so the users have to specify that part somehow and if it is not through (named) attributes during mesh generation, that it should be based on coordinates which is also doable and user-friendly but we don't have it currently in MFEM

@mlstowell, @v-dobrev, @najlkin and @psocratis -- what do you think?

2025-01-15 17:19 UTC, najlkin commented
To the points:

1. I think that function `GetExteriorTrueDofs()` could optionally take the list of boundary attributes or there could be an optional parameter of `GetEssentialTrueDofs()` for selecting only the exterior, like @v-dobrev suggested.
2. Sure, keep it simple.
3. The user-friendliness might depend on the software used for generation of the meshes or what you are used to.
4. I am a bit worried that the logic for selecting one or the other might be too much for Example 1 (considering 2.), but if selection of the boundary based on the named attribute can be reduced to a single line and the next line would be 1. as a backup, I guess it is fine 😉 
5. Unfortunately, all meshes will need to be modified and it will take time to get adopted in user codes, miniapps etc., but with a backup solution it is not critical and the change must be started somewhere 😄 
6. I do not think it is needed now and it is also ambiguous what you want to select by the coordinate and with what tolerance 🤔 .

2025-01-16 19:00 UTC, mlstowell commented
There is a subtle difference between the two approaches derived from `(Par)Mesh::RemoveInternalBoundaries(Array<int> &bdr_marker)` and `(Par)FiniteElementSpace::GetEssentialTrueDofs -- bool remove_interior`. The first is focused on boundary elements where the distinction between interior and exterior is clear. The second is focused on degrees of freedom where the distinction is also clear. However, the second function cannot be implemented using the first function. They can produce different sets of DoFs.

Consider an interior surface whose edge contacts the exterior of the domain e.g. any 2D slice through a 3D domain. Calling `(Par)FiniteElementSpace::GetEssentialTrueDofs -- bool remove_interior = true` with only the interior surface marked should or could be expected to return the DoFs on the boundary of 2D slice.

I can implement `(Par)FiniteElementSpace::GetEssentialTrueDofs -- bool remove_interior = true` by taking the intersection of the results from `(Par)FiniteElementSpace::GetEssentialTrueDofs -- bool remove_interior = false` with those of `(Par)FiniteElementSpace::GetExteriorTrueDofs`. Will this be acceptable?

2025-01-16 23:57 UTC, mlstowell commented
I modified `ex1p.cpp` to show the four proposed solutions (at least those which don't involve altering meshes). Option 3 seems to be the closest to the original implementation. If one of these is acceptable I'll remove the other three and the accompanying logic (and make the analogous changes in `ex1.cpp`).

2025-01-22 01:09 UTC, najlkin commented on mesh/mesh.cpp
> +void Mesh::RemoveInternalBoundaries(Array<int> &bdr_marker, bool excl) const
How about renaming these from `Remove` to `Unmark`? It is more symmetric with the `Mark` functions and also `Remove` a little bit provokes the idea it might modify the mesh 🤔 .

2025-01-22 02:01 UTC, tzanio commented on examples/ex1.cpp
> +
```suggestion
      // Apply boundary conditions on all external boundaries:
      mesh.MarkExternalBoundaries(ess_bdr);
      // Boundary conditions can also be applied based on named attributes:
      // mesh.MarkNamedBoundaries(set_name, ess_bdr)
```

2025-01-22 02:01 UTC, tzanio commented on examples/ex1.cpp
> +
The comment before this code block (step 6) needs to be updated

2025-01-22 02:03 UTC, tzanio commented on examples/ex1.cpp
> +      // mesh.MarkNamedBoundaries(set_name, ess_bdr)
I expected to see an array of named attributes here (due to the Gmsh use case)

2025-01-22 04:25 UTC, mlstowell commented on examples/ex1.cpp
> +      // mesh.MarkNamedBoundaries(set_name, ess_bdr)
I may have misunderstood but I thought the suggestion from @v-dobrev was to use an array of attribute set names (an array of strings) as the argument. However, when I sat down to implement it, it was not clear how a user would input an array of strings from the command line. I chose instead to allow a single set name as the argument. This together with the suggestion that calls to these "Mark*Boundaries" methods only alter the selected attributes seemed to go well together. If some user interface does generate an array of set names this method could be called for each entry in that array.

By "array of named attributes" do you mean an array of attribute numbers like those stored in `Mesh::bdr_attribute_sets`? If so, this would be similar to our `ListToMarker` functions. I can add these if you like:
1) `MarkBoundaries(const Array<int> &attr_set, Array<int> &bdr_marker)` which would mark the selected entries in `bdr_marker` without altering the other entries.
2) `UnmarkBoundaries`(const Array<int> &attr_set, Array<int> &bdr_marker)` which would unmark the selected entries in `bdr_marker` without altering the other entries.

2025-01-22 15:43 UTC, tzanio commented on examples/ex1.cpp
> +      // mesh.MarkNamedBoundaries(set_name, ess_bdr)
Oh, you mean you can call that multiple times for each named attribute! That makes sense and is better than an array. Thanks for clarifying.

2025-01-22 22:55 UTC, v-dobrev requested changes

2025-01-22 22:55 UTC, v-dobrev commented on mesh/mesh.cpp
> +   }
If the output array is bigger than the number of faces, I think it is best to shrink its size to be the number of faces. In other words -- simply call `face_marker.SetSize(num_faces)` where `num_faces = GetNumFaces()`.

2025-01-22 22:55 UTC, v-dobrev commented on mesh/mesh.cpp
> +   for (int b = 0; b < bdr_attributes.Max(); b++)
`bdr_attributes.Max()` is not O(1) method, so it is best to precompute and store this value.

This change applies to other newly added methods too.

2025-01-22 23:02 UTC, v-dobrev commented
This branch has the changes in #4484 but it is not based on that branch. Since #4484 is already merged in `next`, we should probably merge both PRs together in both `next` and in `master`.

2025-01-23 23:29 UTC, mlstowell commented on mesh/mesh.cpp
> +void Mesh::GetExteriorFaceMarker(Array<int> & face_marker) const
I like this idea but `ParMesh::GetExteriorFaceMarker` is `const` while `ParMesh::ExchangeFaceNbrData()` is not. Will it be acceptable to use:
```
const_cast<ParMesh*>(this)->ExchangeFaceNbrData();
```
I can add a note to the doxygen documentation warning that this non-`const` method will be called.

2025-01-23 23:42 UTC, mlstowell commented on mesh/mesh.cpp
> +   for (int b = 0; b < bdr_attributes.Max(); b++)
Good point. Done

2025-01-26 23:33 UTC, tzanio commented
@v-dobrev, @najlkin, @jandrej, @bslazarov and @hughcars -- do you have any additional feedback for @mlstowell ?

2025-01-27 18:28 UTC, v-dobrev commented on mesh/mesh.cpp
> +void Mesh::GetExteriorFaceMarker(Array<int> & face_marker) const
It should be fine to use `const_cast` as you said -- `ExchangeFaceNbrData` does modify some `ParMesh` variables but does not really change the mesh.

Maybe in the future we can make `ExchangeFaceNbrData` `const` if we decide it makes sense -- it will require some variables to be made `mutable`.

2025-01-27 19:22 UTC, v-dobrev commented on mesh/mesh.cpp
> +   }
```suggestion
   face_marker.SetSize(num_faces);
```

2025-01-28 02:01 UTC, najlkin commented on mesh/pmesh.cpp
> +                 MPI_C_BOOL, MPI_LOR, MyComm);
I know it is an old story, but is `MPI_C_BOOL` the right type? 🤔  It should be used for C `_Bool` type. For C++ `bool`, there is `MPI_CXX_BOOL` from MPI 2.2. However, both [seem to be fixed](http://www.unixer.de/blog/index.php/2009/07/30/the-mpi-standard-mpi-22-is-fixed-now/) and have size one 😌 .

2025-01-28 18:36 UTC, mlstowell commented on mesh/pmesh.cpp
> +                 MPI_C_BOOL, MPI_LOR, MyComm);
Fair question. We use this same pattern four other times in `pmesh.cpp` so that's what I followed. However, `MPI_CXX_BOOL` does seem more correct.

2025-01-28 18:40 UTC, v-dobrev approved these changes

2025-01-28 19:36 UTC, tzanio commented
Please mention in `CHANGELOG`

2025-01-28 19:57 UTC, tzanio approved these changes
Thanks @mlstowell, these look great!

2025-01-28 20:01 UTC, tzanio commented
Merged in `next` for testing...

2025-01-29 21:57 UTC, najlkin commented on mesh/pmesh.cpp
> +                 MPI_C_BOOL, MPI_LOR, MyComm);
As discussed, this for a follow-up and would be better to do consistently everywhere. Leaving this not resolved for a future reference.

2025-01-29 21:58 UTC, najlkin approved these changes

2025-01-30 15:48 UTC, tzanio commented
Thanks again for doing this, @mlstowell !

2025-01-30 15:48 UTC, merged